export const HOME_ACTION_TYPES = {
  FETCH_HOME_PRODUCTS_START: "FETCH_HOME_PRODUCTS_START",
  FETCH_HOME_PRODUCTS_SUCCESS: "FETCH_HOME_PRODUCTS_SUCCESS",
  FETCH_HOME_PRODUCTS_FAILED: "FETCH_HOME_PRODUCTS_FAILED",
};
