export const PRODUCTS_ACTION_TYPES = {
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILED: "FETCH_PRODUCT_FAILED",
  FETCH_SEARCH_START: "FETCH_SEARCH_START",
  FETCH_SEARCH_SUCCESS: "FETCH_SEARCH_SUCCESS",
  FETCH_SEARCH_FAILED: "FETCH_SEARCH_FAILED",
  REVIEW_START: "REVIEW_START",
  CREATE_REVIEW_SUCCESS: "CREATE_REVIEW_SUCCESS",
  DELETE_REVIEW_SUCCESS: "DELETE_REVIEW_SUCCESS",
  REVIEW_FAILED: "REVIEW_FAILED",
};
