const SHOP_DATA = [
  {
    id: 1,
    name: "Fire Emblem Engage - Nintendo Switch, Nintendo Switch (OLED Model), Nintendo Switch Lite",
    shortname: "Fire Emblem Engage",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    price: {
      current: 59.99,
      original: 59.99,
    },
    onSale: false,
    rating: 5,
    inStock: true,
    categories: ["Games", "Nintendo Switch"],
  },
  {
    id: 2,
    name: "Nintendo - Switch – OLED Model w/ White Joy-Con - White",
    shortname: "Nintendo Switch",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    price: {
      current: 349.99,
      original: 349.99,
    },
    onSale: false,
    rating: 5,
    inStock: true,
    categories: ["Consoles", "Nintendo Switch"],
  },
  {
    id: 3,
    name: "Sony - PlayStation 5 Console",
    shortname: "Sony Playstation 5",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    price: {
      current: 499.99,
      original: 499.99,
    },
    onSale: false,
    rating: 5,
    inStock: false,
    categories: ["Consoles", "Playstation 5"],
  },
  {
    id: 4,
    name: "Logitech - G203 LIGHTSYNC Wired Optical Gaming Mouse with 8,000 DPI sensor - Black",
    shortname: "Logitech Wired Gaming Mouse",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    price: {
      current: 37,
      original: 50,
    },
    onSale: true,
    rating: 3,
    inStock: false,
    categories: ["Accessories", "PC"],
  },
  {
    id: 5,
    name: "Pokémon Scarlet - Nintendo Switch, Nintendo Switch – OLED Model, Nintendo Switch Lite",
    shortname: "Pokemon Scarlet",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    price: {
      current: 59.99,
      original: 59.99,
    },
    onSale: false,
    rating: 4.5,
    inStock: true,
    categories: ["Games", "Nintendo Switch"],
  },

  {
    id: 6,
    name: "Pokémon Violet - Nintendo Switch, Nintendo Switch – OLED Model, Nintendo Switch Lite",
    shortname: "Pokemon Violet",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    price: {
      current: 59.99,
      original: 59.99,
    },
    onSale: false,
    rating: 4.5,
    inStock: true,
    categories: ["Games", "Nintendo Switch"],
  },
  {
    id: 7,
    name: "Microsoft - Xbox Series X 1TB Console - Black",
    shortname: "Xbox Series X",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    price: {
      current: 499.99,
      original: 499.99,
    },
    onSale: false,
    rating: 5,
    inStock: false,
    categories: ["Consoles", "Xbox"],
  },
];

export default SHOP_DATA;
